apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-24dx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-24dx@sha256:51b13de8c9cba019a8fabfe8989257f88df84be1a407b7231717e849e13d9e8b
        name: my-nodejs
        resources: {}
status: {}
